services:
  graphql:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    container_name: news
    restart: always
    environment:
      - PORT=5400
    ports:
      - 5400:5400

  squid:
    image: ghcr.io/gravitalia/squid:1.0.0
    platform: linux/amd64
    container_name: squid
    restart: on-failure
    ports:
      - 50051:50051
    volumes:
      - ./squid.yml:/config.yaml
