services:
  graphql:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    container_name: news
    restart: always
    environment:
      - PORT=5400
    ports:
      - 5400:5400

  machine_learning:
    build:
      context: ../
      dockerfile: ./docker/ml/Dockerfile
    container_name: machine_learning
    restart: always
    ports:
      - 9001:9001

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=
      - MEILI_NO_ANALYTICS=true
      - MEILI_DB_PATH=/data.ms
    ports:
      - 7700:7700
    volumes:
      - ./data.ms:/data.ms

  squid:
    image: ghcr.io/gravitalia/squid:1.0.0
    platform: linux/amd64
    container_name: squid
    restart: on-failure
    ports:
      - 50051:50051
    volumes:
      - ./squid.yml:/config.yaml

  memcached:
    image: memcached:alpine
    container_name: memcached
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - 11211:11211
