[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
error = { path = "../error" }
meilisearch-sdk = "0.30"
serde = { version = "1", features = ["derive"] }
tokio = { workspace = true }
tracing = "0.1"
