name: news/graphql

on: [push, pull_request]

jobs:
  graphql:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Initialize Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Test GraphQL API
        working-directory: ./graphql
        run: cargo test --all-features
      - name: Clippy
        working-directory: ./graphql
        run: cargo clippy
